export const schema = {
  id: 'movieForm',
  formHeading: 'Create a new movie!',
  submitText: 'Submit!',
  fields: [
    {
      label: 'Title',
      type: 'text',
      id: 'title',
      placeholder: 'title',
      widget: 'input',
      required: true,
    },
    {
      label: 'Director',
      type: 'text',
      id: 'director',
      placeholder: 'Director',
      widget: 'input',
      required: true,
    },
    {
      id: 'genre',
      label: 'Genre',
      type: 'text',
      isMulti: true,
      placeholder: 'Genre',
      widget: 'select',
      required: true,
      options: [
        { value: 'Action', label: 'Action' },
        { value: 'Adventure', label: 'Adventure' },
        { value: 'Animation', label: 'Animation' },
        { value: 'Biography', label: 'Biography' },
        { value: 'Comedy', label: 'Comedy' },
        { value: 'Crime', label: 'Crime' },
        { value: 'Drama', label: 'Drama' },
        { value: 'Family', label: 'Family' },
        { value: 'Fantasy', label: 'Fantasy' },
        { value: 'History', label: 'History' },
        { value: 'Horror', label: 'Horror' },
        { value: 'Music', label: 'Music' },
        { value: 'Musical', label: 'Musical' },
        { value: 'Mystery', label: 'Mystery' },
        { value: 'Romance', label: 'Romance' },
        { value: 'Sci-Fi', label: 'Sci-Fi' },
        { value: 'Thriller', label: 'Thriller' },
        { value: 'War', label: 'War' },
        { value: 'Western', label: 'Western' },
      ]
    },
    {
      label: 'Year',
      type: 'number',
      id: 'year',
      placeholder: 'Year',
      widget: 'input',
      required: true,
    },
    {
      label: 'Rate',
      type: 'text',
      id: 'rate',
      placeholder: 'Rate',
      widget: 'input',
    },
  ]
};